### ISSUE TITLE
Changing custom translation text should also update the english translation and vice versa

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#165]
example: 
```yaml
TOOLBAR:
  items:
  - {action: messages, action_type: click, collapse: false, icon: fa-weixin, text: Learning Journey}
TRANSLATIONS:
  en:
  - {name: learning_journey, value: Learning Journey}
```

If you change "Learning Journey" in the toolbar (or sidebar), the english translation should also be changed.
If you change the english translation value, the toolbar item should be changed as well.
