### ISSUE TITLE
Changes to the default build.yaml files

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#266]
Remove the following constants from the build.yaml files:
```
IOS_DEV_TEAM
IPHONE_DISTRIBUTION
IPHONE_DEVELOPER
```

Since it's no longer used by the iOS build system. Remove all logic to set / update it.

**Comment by bart-at-mobicage** [comment]
There is also new data that needs to be in the default city-app build.yaml files: 
- rogerthat-payment
- ios schemes
- joyn toolbar item
- translations

```
BUILD_CONSTANTS:
  EMBEDDED_APPS:
  - rogerthat-payment
  IOS_SCHEMES:
  - payconiq
  - payconiq.ext
  - joyn
  - joyn-acc
TOOLBAR:
  items:
  - action: reserve1
    action_type: action
    icon: fa-cutlery
    params: {}
    text: Reserve
  - action: __sln__.order
    action_type: action
    icon: fa-shopping-cart
    params: {}
    text: Order
  - action: app
    action_type: open
    icon: joyn
    params:
      android_app_id: com.thanksys.joyn.user
      android_scheme: joyn-acc://
      ios_app_id: id1157594279
      ios_scheme: joyn-acc://
    text: Joyn Loyalty
  - action: qrcode
    action_type: null
    icon: fa-credit-card
    params: {}
TRANSLATIONS:
  en:
  - name: joyn_loyalty
    value: Joyn Loyalty
  nl:
  - name: joyn_loyalty
    value: Joyn Loyalty
```
