### ISSUE TITLE
UI for security stuff

### ISSUE THREAD

**Issue by lucasvanhalst** [rogerthat-platform/plugin-rogerthat-control-center#277]
Add ui for changing 'security' stuff in build.yaml

defaults:
```yaml
  SECURITY:
    APP_KEY_ALGORITHM: ed25519
    APP_KEY_NAME: threefold
    PIN_LOCKED: true
    SECURE: true
```

Remove 'SECURE' from build.yaml in old files , but I think there's already a migration which does that
