### ISSUE TITLE
The collapse param is missing for community services for new apps

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#283]
Eg. be-beringen has 

```
  - action: community_services
    action_type: null
    color: null
    icon: fa-university
    params: {}
    text: City Services
```

instead of

```
  - action: community_services
    action_type: null
    color: null
    icon: fa-university
    params:
      collapse: true
    text: Community Services
```
